name: Publish to PyPi

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
            python-version: '3.x'
      - name: Install pipenv 
        run: |
          python -m pip install --upgrade pip pipenv twine
          pipenv install --deploy --dev --system
      - name: Publish
        env:
          TWINE_USERNAME: ${{ secrets.TWINE_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
        run: |
          pip install twine
          python setup.py sdist
          twine upload dist/* --skip-existing

